//
//  CoinPresenter.swift
//  MarketCoins
//
//  Created by Igor Fortti on 11/09/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CoinPresentationLogic
{
  func presentSomething(response: Coin.Something.Response)
}

class CoinPresenter: CoinPresentationLogic
{
  weak var viewController: CoinDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Coin.Something.Response)
  {
    let viewModel = Coin.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
